-- AlterTable
ALTER TABLE "User" ADD COLUMN     "profile" JSONB;
ALTER TABLE "User" ALTER COLUMN "onboarded" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "otp" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "verified" DROP NOT NULL;
